### ISSUE TITLE
The url https://docus.dev/ requires a visitor password

### ISSUE THREAD

**Issue by JasonLandbridge** [nuxt-themes/docus-starter#6]
Hi there, 

Just to let you know, the url https://docus.dev/ requires a visitor password. Is that intended?

![image](https://user-images.githubusercontent.com/15127381/197353345-1f8ea336-c487-45bf-88f1-de038d3b9551.png)

Cheers!

**Comment by Atinux** [comment]
We plan to open it once we finish our final refactor, will answer soon on this issue

**Comment by alping** [comment]
Any estimate for when this could be ready?

**Comment by Atinux** [comment]
We plan for next week

**Comment by Atinux** [comment]
It's open!
